// 小样用的一天内容：10月13日 周二（第 1 周第 2 天）。[英文, 音标, 中文, 科目]
window.DAY = {
  date: '10月13日 周二',
  sub: '第 1 周 · 第 2 天',
  week: [
    { d: '一', n: 12, k: 'study' }, { d: '二', n: 13, k: 'study', today: true }, { d: '三', n: 14, k: 'study' },
    { d: '四', n: 15, k: 'study' }, { d: '五', n: 16, k: 'study' }, { d: '六', n: 17, k: 'test' }, { d: '日', n: 18, k: 'rest' }
  ],
  S: [
    ['describe', 'dɪˈskraɪb', 'v. 描述', '指令'],
    ['explain', 'ɪkˈspleɪn', 'v. 解释，说明原因', '指令'],
    ['demand', 'dɪˈmɑːnd', 'n. 需求', '经济'],
    ['velocity', 'vəˈlɒsəti', 'n. 速度', '物理'],
    ['denominator', 'dɪˈnɒmɪneɪtə', 'n. 分母', '数学'],
    ['scarcity', 'ˈskeəsəti', 'n. 稀缺', '经济'],
    ['acceleration', 'əkˌseləˈreɪʃn', 'n. 加速度', '物理'],
    ['gradient', 'ˈɡreɪdiənt', 'n. 斜率；梯度', '数学'],
    ['analyse', 'ˈænəlaɪz', 'v. 分析', ''],
    ['approach', 'əˈprəʊtʃ', 'n. 方法；v. 接近', '']
  ],
  R: [
    ['inflation', 'ɪnˈfleɪʃn', 'n. 通货膨胀', '经济'],
    ['current', 'ˈkʌrənt', 'n. 电流；adj. 当前的', '物理'],
    ['mean', 'miːn', 'n. 平均数；v. 意思是', '数学'],
    ['claim', 'kleɪm', 'v. 声称；n. 要求', ''],
    ['relationship', 'rɪˈleɪʃnʃɪp', 'n. 关系', ''],
    ['consumer', 'kənˈsjuːmə', 'n. 消费者', '经济'],
    ['density', 'ˈdensəti', 'n. 密度', '物理'],
    ['integer', 'ˈɪntɪdʒə', 'n. 整数', '数学'],
    ['amount', 'əˈmaʊnt', 'n. 数量，总额', ''],
    ['improve', 'ɪmˈpruːv', 'v. 改善，提高', ''],
    ['output', 'ˈaʊtpʊt', 'n. 产量', '经济'],
    ['charge', 'tʃɑːdʒ', 'n. 电荷；v. 收费', '物理'],
    ['factor', 'ˈfæktə', 'n. 因数；因素', '数学'],
    ['regard', 'rɪˈɡɑːd', 'v. 把…看作', ''],
    ['organisation', 'ˌɔːɡənaɪˈzeɪʃn', 'n. 组织，机构', ''],
    ['region', 'ˈriːdʒən', 'n. 地区', ''],
    ['picture', 'ˈpɪktʃə', 'n. 图片；v. 想象', ''],
    ['travel', 'ˈtrævl', 'v. 旅行', ''],
    ['enjoy', 'ɪnˈdʒɔɪ', 'v. 享受，喜欢', ''],
    ['reduce', 'rɪˈdjuːs', 'v. 减少', '']
  ],
  // 复习：第 1 天学过的词，最后一列 S=默写词 R=认识词
  V: [
    ['calculate', 'ˈkælkjuleɪt', 'v. 计算', '指令', 'S'],
    ['state', 'steɪt', 'v. 写出，简要陈述', '指令', 'S'],
    ['define', 'dɪˈfaɪn', 'v. 下定义', '指令', 'S'],
    ['identify', 'aɪˈdentɪfaɪ', 'v. 指出，找出', '指令', 'S'],
    ['supply', 'səˈplaɪ', 'n. 供给', '经济', 'S'],
    ['force', 'fɔːs', 'n. 力', '物理', 'S'],
    ['equation', 'ɪˈkweɪʒn', 'n. 方程', '数学', 'S'],
    ['opportunity cost', 'ˌɒpəˈtjuːnəti kɒst', 'n. 机会成本', '经济', 'S'],
    ['volume', 'ˈvɒljuːm', 'n. 体积', '数学', 'S'],
    ['assess', 'əˈses', 'v. 评估', '', 'S'],
    ['market', 'ˈmɑːkɪt', 'n. 市场', '经济', 'R'],
    ['speed', 'spiːd', 'n. 速率', '物理', 'R'],
    ['ratio', 'ˈreɪʃiəʊ', 'n. 比，比率', '数学', 'R'],
    ['profit', 'ˈprɒfɪt', 'n. 利润', '经济', 'R'],
    ['energy', 'ˈenədʒi', 'n. 能量', '物理', 'R'],
    ['prime', 'praɪm', 'adj. 质数的；主要的', '数学', 'R'],
    ['support', 'səˈpɔːt', 'v. 支持', '', 'R'],
    ['record', 'ˈrekɔːd', 'n. 记录', '', 'R'],
    ['argue', 'ˈɑːɡjuː', 'v. 争论；主张', '', 'R'],
    ['prepare', 'prɪˈpeə', 'v. 准备', '', 'R'],
    ['seek', 'siːk', 'v. 寻找', '', 'R'],
    ['recent', 'ˈriːsnt', 'adj. 最近的', '', 'R'],
    ['attempt', 'əˈtempt', 'n./v. 尝试', '', 'R'],
    ['suffer', 'ˈsʌfə', 'v. 遭受', '', 'R'],
    ['firm', 'fɜːm', 'n. 企业，公司', '经济', 'R'],
    ['mass', 'mæs', 'n. 质量', '物理', 'R'],
    ['angle', 'ˈæŋɡl', 'n. 角', '数学', 'R'],
    ['nature', 'ˈneɪtʃə', 'n. 自然；本质', '', 'R'],
    ['contain', 'kənˈteɪn', 'v. 包含', '', 'R'],
    ['opinion', 'əˈpɪnjən', 'n. 意见', '', 'R']
  ]
};
